version: '3'

tasks:
  assume-role:
    desc: "Assume AWS pipeline role locally"
    cmds:
      - |
        ROLE_ARN="arn:aws:iam::965220895071:role/TerraformLocalDevRole"
        SESSION_NAME="local-session"
        CREDS=$(aws sts assume-role \
          --role-arn "$ROLE_ARN" \
          --role-session-name "$SESSION_NAME" \
          --duration-seconds 3600)
        export AWS_ACCESS_KEY_ID=$(echo "$CREDS" | jq -r '.Credentials.AccessKeyId')
        export AWS_SECRET_ACCESS_KEY=$(echo "$CREDS" | jq -r '.Credentials.SecretAccessKey')
        export AWS_SESSION_TOKEN=$(echo "$CREDS" | jq -r '.Credentials.SessionToken')
        echo "AWS credentials exported for 1 hour"
